services:
  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pwc_prod_user} -d ${POSTGRES_DB:-pwc_prod}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        while ! nc -z db 5432; do 
          echo 'Database not ready, waiting...' && 
          sleep 2; 
        done &&
        echo 'Database is ready!' &&
        echo 'Running migrations...' &&
        python manage.py migrate --noinput &&
        echo 'Collecting static files...' &&
        python manage.py collectstatic --noinput &&
        echo 'Starting Gunicorn...' &&
        gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    env_file:
      - .env.prod
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot-www:/var/www/certbot:ro
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    environment:
      - EMAIL=${EMAIL:-your-email@domain.com}
      - DOMAIN_NAME=${DOMAIN_NAME}
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL:-your-email@domain.com} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN_NAME}
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:

# prod